version: '3'
services:
  emcee-queue-service:
    image: avitotech/emcee-queue:latest
    container_name: emcee-queue-service
    ports:
      - 41000:41000

  queue-worker:
    image: avitotech/emcee-worker:latest
    env_file:
      - emcee-worker.env
    depends_on:
      - emcee-queue-service
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "2.2" # Here you can configure resources limits depends on features usage for each worker
          memory: "6" # For example, screen recording is very cpu consumption or full hd screen with high api level require more cpu/memory
    devices:
      - "/dev/kvm:/dev/kvm"

  emcee-artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: emcee-artifactory
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - emcee_artifactory:/var/opt/jfrog/artifactory
volumes:
  emcee_artifactory:
